const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
const POST_USER = 'POST_USER';
const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
const POST_USER_FAILURE = 'POST_USER_FAILURE';

const GET_REVIEWS_LIST = 'GET_REVIEWS_LIST';
const GET_REVIEWS_LIST_SUCCESS = 'GET_REVIEWS_LIST_SUCCESS';
const GET_REVIEWS_LIST_FAILURE = 'GET_REVIEWS_LIST_FAILURE';

const POST_REVIEWS_REQUEST = 'POST_REVIEWS_REQUEST';
const POST_REVIEWS_REQUEST_SUCCESS = 'POST_REVIEWS_REQUEST_SUCCESS';
const POST_REVIEWS_REQUEST_FAILURE = 'POST_REVIEWS_REQUEST_FAILURE';

const GET_REQUESTS = 'GET_REQUESTS';
const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
const GET_REQUESTS_FAILURE = 'GET_REQUESTS_FAILURE';

const LOGIN = 'LOGIN';
const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

const SET_USER_ROLES = 'SET_USER_ROLES';

export {
  GET_USERS,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
  POST_USER,
  POST_USER_SUCCESS,
  POST_USER_FAILURE,
  GET_REVIEWS_LIST,
  GET_REVIEWS_LIST_SUCCESS,
  GET_REVIEWS_LIST_FAILURE,
  POST_REVIEWS_REQUEST,
  POST_REVIEWS_REQUEST_SUCCESS,
  POST_REVIEWS_REQUEST_FAILURE,
  LOGIN,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  SET_USER_ROLES,
  GET_REQUESTS,
  GET_REQUESTS_SUCCESS,
  GET_REQUESTS_FAILURE,
};
