const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
const POST_USER = 'POST_USER';
const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
const POST_USER_FAILURE = 'POST_USER_FAILURE';

const GET_TASKSTABLE_SESSIONS = 'GET_TASKSTABLE_SESSIONS';
const GET_TASKSTABLE_SESSIONS_SUCCESS = 'GET_TASKSTABLE_SESSIONS_SUCCESS';
const GET_TASKSTABLE_SESSIONS_FAILURE = 'GET_TASKSTABLE_SESSIONS_FAILURE';

const GET_TASK_SESSION_BY_ID = 'GET_TASK_SESSION_BY_ID';
const UPDATE_TASK_SESSION = 'UPDATE_TASK_SESSION';
const UPDATE_TASK_SESSION_SUCCESS = 'UPDATE_TASK_SESSION_SUCCESS';
const UPDATE_TASK_SESSION_FAILURE = 'UPDATE_TASK_SESSION_FAILURE';
const POST_TASK_SESSIONS = 'POST_TASK_SESSIONS';
const POST_TASK_SESSIONS_SUCCESS = 'POST_TASK_SESSIONS_SUCCESS';
const POST_TASK_SESSIONS_FAILURE = 'POST_TASK_SESSIONS_FAILURE';

const REDIRECT_TO_TASK_SESSIONS = 'REDIRECT_TO_TASK_SESSIONS';
const REDIRECT_TO_TASK_SESSION_FORM = 'REDIRECT_TO_TASK_SESSION_FORM';

const POST_REVIEWS_REQUEST = 'POST_REVIEWS_REQUEST';
const POST_REVIEWS_REQUEST_SUCCESS = 'POST_REVIEWS_REQUEST_SUCCESS';
const POST_REVIEWS_REQUEST_FAILURE = 'POST_REVIEWS_REQUEST_FAILURE';

const GET_REQUESTS = 'GET_REQUESTS';
const GET_REQUESTS_SUCCESS = 'GET_REQUESTS_SUCCESS';
const GET_REQUESTS_FAILURE = 'GET_REQUESTS_FAILURE';

const LOGIN = 'LOGIN';
const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

const SET_USER_ROLES = 'SET_USER_ROLES';

export {
  GET_USERS,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
  POST_USER,
  POST_USER_SUCCESS,
  POST_USER_FAILURE,
  GET_TASKSTABLE_SESSIONS,
  GET_TASKSTABLE_SESSIONS_SUCCESS,
  GET_TASKSTABLE_SESSIONS_FAILURE,
  POST_TASK_SESSIONS,
  POST_TASK_SESSIONS_SUCCESS,
  POST_TASK_SESSIONS_FAILURE,
  REDIRECT_TO_TASK_SESSIONS,
  REDIRECT_TO_TASK_SESSION_FORM,
  GET_TASK_SESSION_BY_ID,
  UPDATE_TASK_SESSION,
  UPDATE_TASK_SESSION_SUCCESS,
  UPDATE_TASK_SESSION_FAILURE,
  POST_REVIEWS_REQUEST,
  POST_REVIEWS_REQUEST_SUCCESS,
  POST_REVIEWS_REQUEST_FAILURE,
  LOGIN,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  SET_USER_ROLES,
  GET_REQUESTS,
  GET_REQUESTS_SUCCESS,
  GET_REQUESTS_FAILURE,
};
