const GET_USERS = 'GET_USERS';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAILURE = 'GET_USERS_FAILURE';
const POST_USER = 'POST_USER';
const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
const POST_USER_FAILURE = 'POST_USER_FAILURE';

const GET_CROSSCHECK_SESSIONS = 'GET_CROSSCHECK_SESSIONS';
const GET_CROSSCHECK_SESSIONS_SUCCESS = 'GET_CROSSCHECK_SESSIONS_SUCCESS';
const GET_CROSSCHECK_SESSIONS_FAILURE = 'GET_CROSSCHECK_SESSIONS_FAILURE';
const POST_CROSSCHECK_SESSION = 'POST_CROSSCHECK_SESSION';
const POST_CROSSCHECK_SESSION_SUCCESS = 'POST_CROSSCHECK_SESSION_SUCCESS';
const POST_CROSSCHECK_SESSION_FAILURE = 'POST_CROSSCHECK_SESSION_FAILURE';

const GET_TASKSTABLE_SESSIONS = 'GET_TASKSTABLE_SESSIONS';
const GET_TASKSTABLE_SESSIONS_SUCCESS = 'GET_TASKSTABLE_SESSIONS_SUCCESS';
const GET_TASKSTABLE_SESSIONS_FAILURE = 'GET_TASKSTABLE_SESSIONS_FAILURE';

const GET_REVIEWS_LIST = 'GET_REVIEWS_LIST';
const GET_REVIEWS_LIST_SUCCESS = 'GET_REVIEWS_LIST_SUCCESS';
const GET_REVIEWS_LIST_FAILURE = 'GET_REVIEWS_LIST_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export {
  GET_USERS,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
  POST_USER,
  POST_USER_SUCCESS,
  POST_USER_FAILURE,
  GET_CROSSCHECK_SESSIONS,
  GET_CROSSCHECK_SESSIONS_SUCCESS,
  GET_CROSSCHECK_SESSIONS_FAILURE,
  GET_TASKSTABLE_SESSIONS,
  GET_TASKSTABLE_SESSIONS_SUCCESS,
  GET_TASKSTABLE_SESSIONS_FAILURE,
  GET_REVIEWS_LIST,
  GET_REVIEWS_LIST_SUCCESS,
  GET_REVIEWS_LIST_FAILURE,
  POST_CROSSCHECK_SESSION,
  POST_CROSSCHECK_SESSION_SUCCESS,
  POST_CROSSCHECK_SESSION_FAILURE,
};
