const GET_USER_BY_GITHUBID = 'GET_USER_BY_GITHUBID';
const GET_USER_BY_GITHUBID_SUCCESS = 'GET_USER_BY_GITHUBID_SUCCESS';
const GET_USER_BY_GITHUBID_FAILURE = 'GET_USER_BY_GITHUBID_FAILURE';

const POST_USER = 'POST_USER';
const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
const POST_USER_FAILURE = 'POST_USER_FAILURE';

const LOGIN = 'LOGIN';
const LOGIN_START = 'LOGIN_START';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const LOGOUT = 'LOGOUT';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

const SET_USER_ROLES = 'SET_USER_ROLES';
const SET_USER_ROLES_SUCCESS = 'SET_USER_ROLES_SUCCESS';

export {
  GET_USER_BY_GITHUBID,
  GET_USER_BY_GITHUBID_SUCCESS,
  GET_USER_BY_GITHUBID_FAILURE,
  POST_USER,
  POST_USER_SUCCESS,
  POST_USER_FAILURE,
  LOGIN,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT,
  LOGOUT_SUCCESS,
  SET_USER_ROLES,
  SET_USER_ROLES_SUCCESS,
};
