const GET_REVIEWS = 'GET_REVIEWS';
const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

const POST_REVIEW = 'POST_REVIEW';
const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

const UPDATE_REVIEW = 'UPDATE_REVIEW';
const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export {
  GET_REVIEWS,
  GET_REVIEWS_SUCCESS,
  GET_REVIEWS_FAILURE,
  POST_REVIEW,
  POST_REVIEW_SUCCESS,
  POST_REVIEW_FAILURE,
  UPDATE_REVIEW,
  UPDATE_REVIEW_SUCCESS,
  UPDATE_REVIEW_FAILURE,
};
