const GET_REVIEWS = 'GET_REVIEWS';
const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

export { GET_REVIEWS, GET_REVIEWS_SUCCESS, GET_REVIEWS_FAILURE };
