const GET_TASKSTABLE_SESSIONS = 'GET_TASKSTABLE_SESSIONS';
const GET_TASKSTABLE_SESSIONS_SUCCESS = 'GET_TASKSTABLE_SESSIONS_SUCCESS';
const GET_TASKSTABLE_SESSIONS_FAILURE = 'GET_TASKSTABLE_SESSIONS_FAILURE';

const GET_TASK = 'GET_TASK';
const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
const GET_TASK_FAILURE = 'GET_TASK_FAILURE';

const UPDATE_TASK_SESSION = 'UPDATE_TASK_SESSION';
const UPDATE_TASK_SESSION_SUCCESS = 'UPDATE_TASK_SESSION_SUCCESS';
const UPDATE_TASK_SESSION_FAILURE = 'UPDATE_TASK_SESSION_FAILURE';

const POST_TASK_SESSIONS = 'POST_TASK_SESSIONS';
const POST_TASK_SESSIONS_SUCCESS = 'POST_TASK_SESSIONS_SUCCESS';
const POST_TASK_SESSIONS_FAILURE = 'POST_TASK_SESSIONS_FAILURE';

export {
  GET_TASKSTABLE_SESSIONS,
  GET_TASKSTABLE_SESSIONS_SUCCESS,
  GET_TASKSTABLE_SESSIONS_FAILURE,
  POST_TASK_SESSIONS,
  POST_TASK_SESSIONS_SUCCESS,
  POST_TASK_SESSIONS_FAILURE,
  GET_TASK,
  GET_TASK_SUCCESS,
  GET_TASK_FAILURE,
  UPDATE_TASK_SESSION,
  UPDATE_TASK_SESSION_SUCCESS,
  UPDATE_TASK_SESSION_FAILURE,
};
